pull_request_rules:
  - name: automatic merge if author is rescom
    conditions:
      - author=restyled-commits
      - status-success=Travis CI - Pull Request
    actions:
      merge:
        method: rebase
  - name: automatic merge if author is resio
    conditions:
      - author=restyled-io
      - status-success=Travis CI - Pull Request
    actions:
      merge:
        method: rebase
